version: '3.1'

services:
#database engine service
  docker-mysql:
    container_name: docker-mysql
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: myroot
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    # ports:
    #   # <Port exposed> : < MySQL Port running inside container>
    #   - 33062:3306

#database admin service
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on: 
      - docker-mysql
    ports:
      - 9090:8080

#First app backend service
  firstapp-back:
    build: .
    restart: always
    container_name: firstapp-back
    ports:
      - 8097:8097
    depends_on:
      - docker-mysql
    links:
      - docker-mysql:app_db