micronaut:
  application:
    name: firtsapp
  server:
    port: 8097
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:mysql://app_db:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: myroot
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true